# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u4f18\u60e0\u5238\u540d\u79f0', max_length=50, unique=True)),
                ('describe', models.CharField(default='', help_text='\u4f18\u60e0\u5238\u63cf\u8ff0', max_length=200)),
                ('url', models.URLField(help_text='\u4f18\u60e0\u5238\u7f51\u5740')),
                ('website', models.CharField(default='', help_text='\u4f18\u60e0\u5238\u7f51\u7ad9', max_length=50)),
                ('classification', models.CharField(default='', help_text='\u4f18\u60e0\u5238\u5206\u7c7b', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='\u4f18\u60e0\u5238\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, help_text='\u4f18\u60e0\u5238\u4fee\u6539\u65f6\u95f4')),
                ('enabled', models.BooleanField(default='True', help_text='\u4f18\u60e0\u5238\u5df2\u7ecf\u542f\u7528')),
            ],
        ),
    ]
